site_name: orvice's wiki


pages:
    - Home: index.md
    - Debian: debian.md
    - Docker: docker.md
    - Git: git.md
    - Cloud: cloud.md

theme:
  name: 'material'

markdown_extensions:
  - admonition